apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: connect
  name: connect-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
  selector:
    app: prod
  type: NodePort
status:
  loadBalancer: {}
